20.03.2024 ver.: 0.1.786.1321 (Error)
lost ref on attacking fleet? after merg and win fleet

MissingReferenceException: The object of type 'GameObject' has been destroyed but you are still trying to access it.
Your script should either check if it is null or you should not destroy the object.
FleetState.CheckOtherAttackersFleetFromOnePlanetToJoin () (at Assets/Code/Monobeh/FleetState.cs:362)
FleetState.FleetStateMeth () (at Assets/Code/Monobeh/FleetState.cs:130)
FleetState.Update () (at Assets/Code/Monobeh/FleetState.cs:50)